#ifndef CHIP8_CONSTANTS_H
#define CHIP8_CONSTANTS_H

#define CHIP8_PROGRAM_START 0x200
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_STACK_SIZE 16
#define CHIP8_REGISTER_SIZE 16
#define CHIP8_SCREEN_WIDTH 64
#define CHIP8_SCREEN_HEIGHT 32
#define CHIP8_SCREEN_SIZE CHIP8_SCREEN_WIDTH*CHIP8_SCREEN_HEIGHT

#endif /* CHIP8_CONSTANTS_H */
